### ISSUE TITLE
Plz add install/compatibility note when possible

### ISSUE THREAD

**Issue by tukoz** [JustOff/dismiss-the-overlay#2]
Hi! Renaming the zip to xpi does produce a « couldn't install, file's corrupted » message. Unpacking and packing it recursively with p7zip I didn't succeed either; yeah, archived the files directly and recursively, not the containing folder.
Maybe a couple words on how to install would help some around.

Tested for/with Palemoon 27.4.2 browser.

**Comment by JustOff** [comment]
The installation package is located [here](https://github.com/JustOff/behind-the-overlay-me/releases).

**Comment by tukoz** [comment]
Thanks you for the link! Couldn't and still can't find it without that direct hint.

**Comment by JustOff** [comment]
![palemoon_2017-09-22_16-59-02](https://user-images.githubusercontent.com/340855/30747960-745ee386-9fb7-11e7-979f-235abb39034f.png)
:stuck_out_tongue_winking_eye:
