### ISSUE TITLE
Hotkey/shortcut possible?

### ISSUE THREAD

**Issue by Gittyperson** [JustOff/dismiss-the-overlay#3]
Don't know if it's technically feasible, but an assignable key press would be very convenient to have, as an alternative to point'n'click.

**Comment by JustOff** [comment]
Well, I'm a little lazy to provide a customizable key combination, but Ctrl+Shift+X is free and seems suitable to me, considering exactly this combination is used in a similar [extension for Chrome](https://chrome.google.com/webstore/detail/behindtheoverlay/ljipkdpcjbmhkdjjmbbaggebcednbbme).

**Comment by Gittyperson** [comment]
Thanks, that would be great. Just checked my fairly extensive list of programs and that combination seems indeed free (it does something to the text formatting right here in this comment box though).

**Comment by JustOff** [comment]
Resolved in [1.0.2](https://github.com/JustOff/behind-the-overlay-me/releases/tag/1.0.2).

PS: It's now [listed on APMO](https://addons.palemoon.org/addon/behind-the-overlay-me/).
