### ISSUE TITLE
Possibility of Automatic mode?

### ISSUE THREAD

**Issue by dtoxic47** [JustOff/dismiss-the-overlay#4]
Like the title says, an option to toggle auto mode so it would remove any overlay on site opened/during load. or to black overlays completley

**Comment by JustOff** [comment]
This function is very unlikely to be implemented, due to the expected large number of false positives.

**Comment by OmegaPhil** [comment]
Putting a 'me too' here - it would be useful to be able to whitelist sites where overlay removal can be done automatically, e.g. Wikia.
