### ISSUE TITLE
Button Name

### ISSUE THREAD

**Issue by billmcct** [JustOff/dismiss-the-overlay#5]
JustOff could you please shorten the button name? I am visually impaired and use text buttons and the button is using almost 2 inches of space. I think just "Remove Overlay" would be good.
Thanks.
Bill

**Comment by JustOff** [comment]
Do you use text only buttons or icon and text?

**Comment by billmcct** [comment]
JustOff, I use text only buttons.
I just had to use FF to post this. Go figure.

**Comment by JustOff** [comment]
Well, then add this code to [UserChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css)
```
toolbar:not([mode="icons"]) > #action-button--behind-the-overlay-meoffjustoff-behindtheoverlay-button .toolbarbutton-text {
  display: none !important;
}
toolbar:not([mode="icons"]) > #action-button--behind-the-overlay-meoffjustoff-behindtheoverlay-button:after {
  content: " Remove Overlay" !important;
  display: -moz-box !important;
}
```
and restart browser.

PS: Don't forget to add `@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");` at the beginning of `UserChrome.css` if you create it from scratch.

**Comment by billmcct** [comment]
Thank you kindly good sir.

Bill

**Comment by JustOff** [comment]
You are welcome)
