### ISSUE TITLE
 dismiss-the-overlay disappears from Pale Moon Status Bar

### ISSUE THREAD

**Issue by Zackman1000** [JustOff/dismiss-the-overlay#6]
This issue has occurred repeatedly during the past three weeks. If I disable dismiss-the-overlay in about:addons, then restart Pale Moon and enable dismiss-the-overlay again, the icon will reappear and I can use it again, only to find that it has disappeared later.

Is there a keyboard shortcut that I could use to call up dismiss-the-overlay when I no longer have it available in the Status Bar?

Thank you.

**Comment by JustOff** [comment]
The disappearing button may be due to a conflict with other extensions. You can use the combination `Ctrl + Shift + x` or try to find a different position for the button on the status bar, i.e. swap it with other buttons.
